# Generated by Django 4.0.6 on 2022-12-11 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='file',
            field=models.FileField(upload_to='C:/Users/AKAM/Desktop/React/week2/djangoproject/reactapp/src/uploads/posts'),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='C:/Users/AKAM/Desktop/React/week2/djangoproject/reactapp/src/uploads/story')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
