# Generated by Django 4.0.6 on 2022-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0010_user_profile_alter_comment_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(null=True, upload_to='C:/Users/AKAM/Desktop/React/week2/djangoproject/reactapp/src/uploads/profile'),
        ),
    ]
