# Generated by Django 4.0.6 on 2022-12-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0011_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
