# Generated by Django 4.0.6 on 2022-12-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0015_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='discount_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='is_premium',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='is_z',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='lang',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='repo',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='zdescription',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='zfile',
            field=models.FileField(default=0, upload_to='C:/Users/AKAM/Desktop/React/week2/djangoproject/reactapp/src/uploads/zpostfile'),
            preserve_default=False,
        ),
    ]
