# Generated by Django 4.0.6 on 2023-01-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0020_alter_premiumpurchases_postid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='downloadsCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
