# Generated by Django 4.0.6 on 2023-01-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0022_alldownloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='downloadsCount',
            field=models.IntegerField(default=0),
        ),
    ]
