# Generated by Django 4.0.6 on 2023-01-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0024_storywatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
