# Generated by Django 4.0.6 on 2023-01-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0026_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_bussiness',
        ),
    ]
