# Generated by Django 4.0.6 on 2023-01-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0028_user_is_verfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
