# Generated by Django 4.0.6 on 2023-01-27 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djadmin', '0003_remove_postreports_user_bussinessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usse', to=settings.AUTH_USER_MODEL),
        ),
    ]
